### PR TITLE
fix the readme credits

### PR DESCRIPTION
**Pull request by VillainsRule**
@rxzyx and @cph101 skidded off @Minesraft2, if you'd like to avoid a DMCA, i'd fix the credits!

### CODE REVIEW

**Comment by CPScript** [comment]
damn... i don't think you should take credit away from everyone....

**Comment by Minesraft2** [comment]
bro you already mentioned me I've been watching the whole thing

**Comment by CPScript** [comment]
lol @Minesraft2 what is your opinion on this mater?

**Comment by Minesraft2** [comment]
The pr is valid but the way he does it is not

**Comment by CPScript** [comment]
> 🤡 alright ill speak with minesraft after school, you'll enjoy the dmca!

doesn't realy matter to me, im not the one who skidded his stuff

**Comment by CPScript** [comment]
> The pr is valid but the way he does it is not

what do you mean by this?

**Comment by Minesraft2** [comment]
> > The pr is valid but the way he does it is not
> 
> 
> 
> what do you mean by this?

rzx and cph did skid from my work, but i dont think calling people retarded is gonna get us anywhere

**Comment by CPScript** [comment]
> rzx and cph did skid from my work, but i dont think calling people retarded is gonna get us anywhere

lol... would you like me to request that the owner of this repo takes away your work? also idk why @VillainsRule is getting triggered over summ so stupid.... 🤣 (i can also credit you, if you would like for your work to stay)

**Comment by CPScript** [comment]
> if my work is taken down the whole repo almost would be gone, plus, it's all skidded from the outdated code i made on therealgliz's repo

well, i can take away your work, BUT im not the owner, just kinda a manager... so you would have to ask @Hankypoo7 if you want to do summ about this... If you're fine with it being here, i can give you credit...

**Comment by Minesraft2** [comment]
I mean, I'd prefer if it wasn't up, but I also don't see any purpose DMCAing outdated code

**Comment by CPScript** [comment]
OK, well, you would have to bring that up with the owner... Because I can't do anything about that.

**Comment by CPScript** [comment]
imma go ahead and close this pull request!

**Comment by Hankypoo7** [comment]
yo im here im stupid sorry

**Comment by Hankypoo7** [comment]
bruh imma be honest i dont really care anymore im just some random 13 year old kid in the middle of iowa

**Comment by Hankypoo7** [comment]
ive been busy with baseball but @Minesraft2 what do you want me to do

**Comment by Minesraft2** [comment]
honestly i dont care, but it'd be nice for everything to be taken down. They're old scripts anyway

**Comment by Hankypoo7** [comment]
aight
can i just archive it?

**Comment by Hankypoo7** [comment]
@VillainsRule stop being a dick

**Comment by Minesraft2** [comment]
go for it

**Comment by Hankypoo7** [comment]
@Minesraft2 thank you, i apologize for compiling a bunch of hacks that i didnt have permission to use

**Pull request closed without merging**
