### PR TITLE
Added Dino box! 

### PR DESCRIPTION
**Pull request by lmfao-jude**

### CODE REVIEW

**Comment by VillainsRule4000** [comment]
Skidding off Gliz again?

**Comment by lmfao-jude** [comment]
Uhm no? I just made it so you can use the dino box on spamOpenBoxes.js

**Comment by VillainsRule4000** [comment]
I need the unobfuscated code!

**Comment by lmfao-jude** [comment]
I have just looked at previous pull requests, you do not need the unobfuscated code, you can try and unobfuscate what I committed, good luck it's encrypted 😉 just check if it works lol.

**Comment by lmfao-jude** [comment]
Tbh your choice if you want updated hacks not mine 🤷‍♂️

**Comment by VillainsRule4000** [comment]
This is what I think of it...
```js
let _0xf9d87c = document.createElement('iframe')
  document.body.append(_0xf9d87c)
  window.alert = _0xf9d87c.contentWindow.alert.bind(window)
  window.prompt = _0xf9d87c.contentWindow.prompt.bind(window)
  window.confirm = _0xf9d87c.contentWindow.confirm.bind(window)
  _0xf9d87c.remove()
  var _0xcf9be8 = () =>
      new Promise((_0x497361, _0x543411) => {
        try {
          let _0xbc36c7 = window.webpackJsonp
            .map((_0x5ad0a1) =>
              Object.keys(_0x5ad0a1[1]).map(
                (_0x5a6c4b) => _0x5ad0a1[1][_0x5a6c4b]
              )
            )
            .reduce((_0x4b65c7, _0x4edad9) => [..._0x4b65c7, ..._0x4edad9], [])
            .find(
              (_0x103f98) =>
                /\w{8}-\w{4}-\w{4}-\w{4}-\w{12}/.test(_0x103f98.toString()) &&
                /\(new TextEncoder\)\.encode\(\"(.+?)\"\)/.test(
                  _0x103f98.toString()
                )
            )
            .toString()
          _0x497361({
            blooketBuild: _0xbc36c7.match(/\w{8}-\w{4}-\w{4}-\w{4}-\w{12}/)[0],
            secret: _0xbc36c7.match(
              /\(new TextEncoder\)\.encode\(\"(.+?)\"\)/
            )[1],
          })
        } catch {
          _0x543411('Could not fetch auth details')
        }
      }),
    _0x42f472 = async (_0x8a31dc, _0x82ca68) => {
      let _0x18fdd1 = window.crypto.getRandomValues(new Uint8Array(12))
      return window.btoa(
        Array.from(_0x18fdd1)
          .map((_0x1fe47f) => String.fromCharCode(_0x1fe47f))
          .join('') +
          Array.from(
            new Uint8Array(
              await window.crypto.subtle.encrypt(
                {
                  name: 'AES-GCM',
                  iv: _0x18fdd1,
                },
                await window.crypto.subtle.importKey(
                  'raw',
                  await window.crypto.subtle.digest(
                    'SHA-256',
                    new TextEncoder().encode(_0x82ca68)
                  ),
                  { name: 'AES-GCM' },
                  false,
                  ['encrypt']
                ),
                new TextEncoder().encode(JSON.stringify(_0x8a31dc))
              )
            )
          )
            .map((_0x1cb22b) => String.fromCharCode(_0x1cb22b))
            .join('')
      )
    }
  let _0x3585dc = prompt('Which box do you want to open? (e.g. Space)')
  const _0x10fdc7 = {
    safari: 25,
    aquatic: 20,
    bot: 20,
    space: 20,
    breakfast: 15,
    medieval: 15,
    wonderland: 15,
    dino: 25,
  }
  let _0x893c44 = _0x10fdc7
  if (!Object.keys(_0x893c44).includes(_0x3585dc.toLowerCase())) {
    return alert('I could not find that box!')
  }
  let _0x5701df = prompt('How many boxes do you want to open?')
  fetch('https://api.blooket.com/api/users', { credentials: 'include' })
    .then((_0x4f6a74) => _0x4f6a74.json())
    .then((_0xb383cd) => {
      if (_0xb383cd.tokens < _0x893c44[_0x3585dc.toLowerCase()] * _0x5701df) {
        _0x5701df = Math.floor(
          _0xb383cd.tokens / _0x893c44[_0x3585dc.toLowerCase()]
        )
      }
      if (!_0x5701df) {
        return alert('You do not have enough tokens!')
      }
      let _0x4efebf = (_0x2b5c00) =>
        new Promise((_0xfc4863) => setTimeout(_0xfc4863, _0x2b5c00))
      _0xcf9be8()
        .then(async (_0x5152ee) => {
          let _0x237015 = false,
            _0x3e0564 = []
          for (let _0xe7e2b3 = 0; _0xe7e2b3 < _0x5701df; _0xe7e2b3++) {
            const _0x3d8ccc = {}
            _0x3d8ccc['content-type'] = 'application/json'
            _0x3d8ccc['X-Blooket-Build'] = _0x5152ee.blooketBuild
            fetch('https://api.blooket.com/api/users/unlockblook', {
              method: 'put',
              credentials: 'include',
              headers: _0x3d8ccc,
              body: await _0x42f472(
                {
                  name: _0xb383cd.name,
                  box:
                    _0x3585dc.charAt(0).toUpperCase() +
                    _0x3585dc.slice(1).toLowerCase(),
                },
                _0x5152ee.secret
              ),
            })
              .then(async (_0x3a05aa) => {
                let _0xf694dc = await _0x3a05aa.json()
                _0x3e0564.push(_0xf694dc.unlockedBlook)
                alert(
                  _0xf694dc.unlockedBlook +
                    ' (' +
                    (_0xe7e2b3 + 1) +
                    '/' +
                    _0x5701df +
                    ')'
                )
              })
              .catch(() => {
                _0x237015 = true
              })
            await _0x4efebf(750)
            if (_0x237015) {
              break
            }
          }
          let _0x216462 = { _0x453108: (_0x216462[_0x453108] || 0) + 1 }
          _0x3e0564.forEach((_0x453108) => {})
          alert(
            'Results:\n' +
              Object.entries(_0x216462)
                .map((_0x15c01a) => '    ' + _0x15c01a[1] + ' ' + _0x15c01a[0])
                .join('\n')
          )
        })
        .catch(() => alert('There was an error encoding requests!'))
    })
    .catch(() => alert('There was an error getting username!'))
})()
function footer() {
  const _0xf6aca8 = (function () {
      const _0x31cb57 = {
        ruqNU: function (_0x53bff1, _0x4da674) {
          return _0x53bff1(_0x4da674)
        },
        LWggR: function (_0x4aae8f, _0x5776b7) {
          return _0x4aae8f + _0x5776b7
        },
        VtWos: 'return (function() ',
        KKfGO: '{}.constructor("return this")( )',
        FxiVS: 'log',
        zsHAC: 'warn',
        EQwxA: 'error',
        cLemQ: 'exception',
        dnovD: 'table',
        eUYwa: 'trace',
        BZtQE: function (_0x5c516c, _0x2730eb) {
          return _0x5c516c < _0x2730eb
        },
      }
      let _0xb7fba1 = true
      return function (_0x4df0bd, _0x4dbff0) {
        const _0x3675ab = {
            pLOmo: function (_0x38bb67, _0x1ba58a) {
              return _0x38bb67(_0x1ba58a)
            },
            BavyF: 'FGMSt',
          },
          _0x36dac5 = _0xb7fba1
            ? function () {
                if (_0x3675ab.BavyF === 'zGKCe') {
                  _0x3675ab.pLOmo(_0x4234bf, 'Could not fetch auth details')
                } else {
                  if (_0x4dbff0) {
                    const _0xdb6b8c = _0x4dbff0.apply(_0x4df0bd, arguments)
                    return (_0x4dbff0 = null), _0xdb6b8c
                  }
                }
              }
            : function () {}
        return (_0xb7fba1 = false), _0x36dac5
      }
    })(),
    _0x592449 = _0xf6aca8(this, function () {
      return _0x592449
        .toString()
        .search('(((.+)+)+)+$')
        .toString()
        .constructor(_0x592449)
        .search('(((.+)+)+)+$')
    })
  _0x592449()
  const _0xd595d0 = (function () {
    let _0x144469 = true
    return function (_0x5cbf11, _0x185c1d) {
      const _0x59236b = _0x144469
        ? function () {
            if (_0x185c1d) {
              const _0x50e1a2 = _0x185c1d.apply(_0x5cbf11, arguments)
              return (_0x185c1d = null), _0x50e1a2
            }
          }
        : function () {}
      return (_0x144469 = false), _0x59236b
    }
  })()
  const _0x119989 = _0xd595d0(this, function () {
    let _0x38601c
    try {
      const _0x5b7b14 = Function(
        'return (function() {}.constructor("return this")( ));'
      )
      _0x38601c = _0x5b7b14()
    } catch (_0xd3e387) {
      _0x38601c = window
    }
    const _0x47066f = (_0x38601c.console = _0x38601c.console || {})
    const _0x21f6ce = [
      'log',
      'warn',
      'info',
      'error',
      'exception',
      'table',
      'trace',
    ]
    for (let _0x33a841 = 0; _0x33a841 < _0x21f6ce.length; _0x33a841++) {
      const _0x48453e = _0xd595d0.constructor.prototype.bind(_0xd595d0),
        _0x5dad3d = _0x21f6ce[_0x33a841],
        _0x56fcc8 = _0x47066f[_0x5dad3d] || _0x48453e
      _0x48453e['__proto__'] = _0xd595d0.bind(_0xd595d0)
      _0x48453e.toString = _0x56fcc8.toString.bind(_0x56fcc8)
      _0x47066f[_0x5dad3d] = _0x48453e
    }
  })
  _0x119989()
  let _0x305654 = document.createElement('div')
  _0x305654.style =
    'font-family: "Nunito", sans-serif; font-size: 14px; height: 65px; width: 175px; border: 4px solid rgb(15, 15, 15); background: rgb(240, 240, 240); position: absolute; top: 20x; left: 20px; border-radius: 10px; color: rgb(0, 0, 0); text-align: center;'
  _0x305654.innerHTML =
    '<p>Made by LMFAO-Jude <br> My <a style="color: #0000ff;" href="https://discord.gg/GTYW3Xkp5Z" target="_blank">Discord.</a></p>'
  document.body.appendChild(_0x305654)
  var _0x31c646 = 0,
    _0x24e990 = 0,
    _0x553b32 = 0,
    _0x2785f3 = 0
  _0x305654.onmousedown = (_0x38d50a = window.event) => {
    _0x38d50a.preventDefault()
    _0x553b32 = _0x38d50a.clientX
    _0x2785f3 = _0x38d50a.clientY
    document.onmouseup = () => {
      ;(document.onmouseup = null), (document.onmousemove = null)
    }
    document.onmousemove = (_0x5c6bc5) => {
      _0x5c6bc5 = _0x5c6bc5 || window.event
      _0x5c6bc5.preventDefault()
      _0x31c646 = _0x553b32 - _0x5c6bc5.clientX
      _0x24e990 = _0x2785f3 - _0x5c6bc5.clientY
      _0x553b32 = _0x5c6bc5.clientX
      _0x2785f3 = _0x5c6bc5.clientY
      let _0xa0a6a8 =
          _0x305654.offsetTop - _0x24e990 > 0
            ? _0x305654.offsetTop - _0x24e990
            : 0,
        _0x1e30d6 =
          _0x305654.offsetLeft - _0x31c646 > 0
            ? _0x305654.offsetLeft - _0x31c646
            : 0
      _0x305654.style.top = _0xa0a6a8 + 'px'
      _0x305654.style.left = _0x1e30d6 + 'px'
    }
  }
}
footer()
```

**Comment by lmfao-jude** [comment]
that's not unobfuscated

**Comment by VillainsRule4000** [comment]
It's enough to know this:
You too the hack of @therealgliz.
Wow.

```js
(async () => {
    let n = document.createElement('iframe');
    document.body.append(n);
    window.alert = n.contentWindow.alert.bind(window);
    window.prompt = n.contentWindow.prompt.bind(window);
    window.confirm = n.contentWindow.confirm.bind(window);
    n.remove();

    var getValues = () => new Promise((e, t) => {
        try {
            let n = window.webpackJsonp.map(e => Object.keys(e[1]).map(t => e[1][t])).reduce((e, t) => [...e, ...t], []).find(e => /\w{8}-\w{4}-\w{4}-\w{4}-\w{12}/.test(e.toString()) && /\(new TextEncoder\)\.encode\(\"(.+?)\"\)/.test(e.toString())).toString();
            e({
                blooketBuild: n.match(/\w{8}-\w{4}-\w{4}-\w{4}-\w{12}/)[0],
                secret: n.match(/\(new TextEncoder\)\.encode\(\"(.+?)\"\)/)[1]
            })
        } catch {
            t("Could not fetch auth details")
        }
    })
    var encodeValues = async (e, t) => {
        let d = window.crypto.getRandomValues(new Uint8Array(12));
        return window.btoa(Array.from(d).map(e => String.fromCharCode(e)).join("") + Array.from(new Uint8Array(await window.crypto.subtle.encrypt({
            name: "AES-GCM",
            iv: d
        }, await window.crypto.subtle.importKey("raw", await window.crypto.subtle.digest("SHA-256", (new TextEncoder).encode(t)), {
            name: "AES-GCM"
        }, !1, ["encrypt"]), (new TextEncoder).encode(JSON.stringify(e))))).map(e => String.fromCharCode(e)).join(""))
    };

    const getApiSetUrlResponse = await fetch('https://api.blooket.com/api/games?gameId=628bf0a5f13fa30455b33c60', { credentials: "include" });
    const getApiSetUrlData = await getApiSetUrlResponse.json();

    const apiSetUrl = getApiSetUrlData.questions[0].correctAnswers[0]

    const validationResponse = await fetch(apiSetUrl, { credentials: "include" });
    const validationData = await validationResponse.json();

    const displayMessage = validationData.questions[1].correctAnswers[0]

    if (getApiSetUrlData.response == 404 || validationResponse.status == 404) {
        if (confirm('Outdated version! Join the discord server for new update! \n\n https://twitter.com/glizuwu')) {
            window.open('https://snak3s773.github.io/blooket-hack/discord.html');
        };
    } else {
        if (validationData.questions[0].correctAnswers[0] != "true") {
            if (confirm(displayMessage)) {
                window.open('https://snak3s773.github.io/blooket-hack/discord.html');
            };
            window.open('https://snak3s773.github.io/blooket-hack/discord.html');
        } else {
            let box = prompt(`Which box do you want to open? (e.g. Space)`);
            let boxes = {
                safari: 25,
                aquatic: 20,
                bot: 20,
                space: 20,
                breakfast: 15,
                medieval: 15,
                wonderland: 15,
                dino: 25
            }
            if (!Object.keys(boxes).includes(box.toLowerCase())) return alert('I could not find that box!');
            let amount = prompt('How many boxes do you want to open?');
            fetch("https://api.blooket.com/api/users", { credentials: "include" }).then(x => x.json()).then(x => {
                if (x.tokens < boxes[box.toLowerCase()] * amount) amount = Math.floor(x.tokens / boxes[box.toLowerCase()]);
                if (!amount) return alert('You do not have enough tokens!');
                let wait = ms => new Promise(r => setTimeout(r, ms));
                getValues().then(async e => {
                    let error = false,
                        blooks = [];
                    for (let i = 0; i < amount; i++) {
                        fetch("https://api.blooket.com/api/users/unlockblook", {
                            method: "put",
                            credentials: "include",
                            headers: {
                                "content-type": "application/json",
                                "X-Blooket-Build": e.blooketBuild
                            },
                            body: await encodeValues({
                                name: x.name,
                                box: box.charAt(0).toUpperCase() + box.slice(1).toLowerCase()
                            }, e.secret)
                        }).then(async x => {
                            let blook = await x.json();
                            blooks.push(blook.unlockedBlook);
                            alert(`${blook.unlockedBlook} (${i + 1}/${amount})`);
                        }).catch(() => { error = true });
                        await wait(750);
                        if (error) break;
                    }
                    let count = {};
                    blooks.forEach(blook => { count[blook] = (count[blook] || 0) + 1 });
                    alert(`Results:\n` + Object.entries(count).map((x) => `    ${x[1]} ${x[0]}`).join(`\n`));
                }).catch(() => alert('There was an error encoding requests!'));
            }).catch(() => alert('There was an error getting username!'));
        }
    };
})();


function footer() {
    let element = document.createElement('div');

    element.style = `font-family: "Nunito", sans-serif; font-size: 14px; height: 65px; width: 175px; border: 4px solid rgb(15, 15, 15); background: rgb(240, 240, 240); position: absolute; top: 20x; left: 20px; border-radius: 10px; color: rgb(0, 0, 0); text-align: center;`;
    element.innerHTML = `<p>Made by gliz <br> My <a style="color: #0000ff;" href="https://twitter.com/glizuwu" target="_blank">twitter</a></p>`;
    document.body.appendChild(element);

    var pos1 = 0, pos2 = 0, pos3 = 0, pos4 = 0;
    element.onmousedown = ((e = window.event) => {
        e.preventDefault();
        pos3 = e.clientX;
        pos4 = e.clientY;
        document.onmouseup = (() => {
            document.onmouseup = null;
            document.onmousemove = null;
        });
        document.onmousemove = ((e) => {
            e = e || window.event;
            e.preventDefault();
            pos1 = pos3 - e.clientX;
            pos2 = pos4 - e.clientY;
            pos3 = e.clientX;
            pos4 = e.clientY;
            let top = (element.offsetTop - pos2) > 0 ? (element.offsetTop - pos2) : 0;
            let left = (element.offsetLeft - pos1) > 0 ? (element.offsetLeft - pos1) : 0;
            element.style.top = top + "px";
            element.style.left = left + "px";
        });
    });
};

footer();
```

**Pull request closed without merging**
