### PR TITLE
Update AddTokensXP.js

### PR DESCRIPTION
**Pull request by vantr-o**
I will add more later, this is just to add everyone's most needed hack.

### CODE REVIEW

**Comment by vantr-o** [comment]
You can test it if you find it sketchy.

**Comment by VillainsRule4000** [comment]
@GooseterV Your thoughts on this PR?

**Comment by VillainsRule4000** [comment]
Where did you find this script?

**Comment by vantr-o** [comment]
> Where did you find this script?

I messed around with gliz's code and encoder, and made it only add tokens rather than add a footer.

```
(async () => {
    let n = document.createElement('iframe');
    document.body.append(n);
    window.alert = n.contentWindow.alert.bind(window);
    window.prompt = n.contentWindow.prompt.bind(window);
    window.confirm = n.contentWindow.confirm.bind(window);
    n.remove();

    var getValues = () => new Promise((e, t) => {
        try {
            let n = window.webpackJsonp.map(e => Object.keys(e[1]).map(t => e[1][t])).reduce((e, t) => [...e, ...t], []).find(e => /\w{8}-\w{4}-\w{4}-\w{4}-\w{12}/.test(e.toString()) && /\(new TextEncoder\)\.encode\(\"(.+?)\"\)/.test(e.toString())).toString();
            e({
                blooketBuild: n.match(/\w{8}-\w{4}-\w{4}-\w{4}-\w{12}/)[0],
                secret: n.match(/\(new TextEncoder\)\.encode\(\"(.+?)\"\)/)[1]
            })
        } catch {
            t("Could not fetch auth info")
        }
    })
    var encodeValues = async (e, t) => {
        let d = window.crypto.getRandomValues(new Uint8Array(12));
        return window.btoa(Array.from(d).map(e => String.fromCharCode(e)).join("") + Array.from(new Uint8Array(await window.crypto.subtle.encrypt({
            name: "AES-GCM",
            iv: d
        }, await window.crypto.subtle.importKey("raw", await window.crypto.subtle.digest("SHA-256", (new TextEncoder).encode(t)), {
            name: "AES-GCM"
        }, !1, ["encrypt"]), (new TextEncoder).encode(JSON.stringify(e))))).map(e => String.fromCharCode(e)).join(""))
    };
            fetch("https://api.blooket.com/api/users", { credentials: "include" }).then(x => x.json()).then(x => {
                getValues().then(async e => {
                    fetch("https://api.blooket.com/api/users/add-rewards", {
                        method: "put",
                        credentials: "include",
                        headers: {
                            "content-type": "application/json",
                            "X-Blooket-Build": e.blooketBuild
                        },
                        body: await encodeValues({
                            name: x.name,
                            addedTokens: 500,
                            addedXp: 300
                        }, e.secret)
                    });
                    fetch("https://api.blooket.com/api/users/add-rewards", {
                        method: "put",
                        credentials: "include",
                        headers: {
                            "content-type": "application/json",
                            "X-Blooket-Build": e.blooketBuild
                        },
                        body: await encodeValues({
                            name: x.name,
                            addedTokens: 500,
                            addedXp: 300
                        }, e.secret)
                    }).then(() => alert('Added daily tokens, and XP!')).catch(() => alert('There was an error adding rewards!'));;
                }).catch(() => alert('There was an error encoding your request.'));
            }).catch(() => alert('There was an error fetching name.'));
})();

```

I know it looks similar but this was what I have made myself.

**Comment by VillainsRule4000** [comment]
It pretty much is the same. Just remove the function `footer()`. It's not hard to skid off gliz, at least give some credit in the README file.

**Comment by vantr-o** [comment]
I just thought add tokens and xp was what is most used so why not update it, anyway it's fine if you don't merge it.

**Comment by VillainsRule4000** [comment]
Also, we are not skids. Keeping the footer is customary, gliz made the script, give them credit.

**Comment by vantr-o** [comment]
> It pretty much is the same. Just remove the function `footer()`. It's not hard to skid off gliz, at least give some credit in the README file.

I saw you had credits to Gliz in the readme so i didn't mess with that, but I did make these it's just api looks alike.

**Comment by vantr-o** [comment]
i still wander why lol jude tried to impersonate gliz..

**Comment by vantr-o** [comment]
> lso, you and gliz have the EXACT same code.

Who get's GitHub pro on an alt, it's not the exact same as well, you can notice differences.

**Comment by VillainsRule4000** [comment]
Who gets Github and has a fully configured profile AND pro on a 3 day old account?

**Comment by vantr-o** [comment]
> Who gets Github and has a fully configured profile AND pro on a 3 day old account?

I've had an account before. Never been involved in this just heard it around, I made a new account to claim my pro account with my school because an [old account](https://github.com/NotJvdz3) was claimed with my old school email so I couldn't use that, I do have the same name as lol but that's just chance of this happening, I already had a profile Readme.md on my old account which is now deleted, I only claimed the pro account to use jetbrains products to host websites and discord bots easier, I only use it for webstorm, and pycharm enterprise.

**Comment by vantr-o** [comment]
And as I said before why would I use pro on a alt.

**Pull request closed without merging**
